##Create Transacitions
post http://localhost:8080/transactions
Content-Type: application/json

{
    "prompt": "Hoje eu paguei  um conta de internet no valor de 100 reais"
}

###
#get transaction recents
get http://localhost:8080/transactions/recent

###
# get transaction all
get http://localhost:8080/transactions?name=&categories=&pageIndex=0
